POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBldGVyIiwiaWQiOiI2NzhmOGNkMTI4MDBkYjQ1Y2QyNzkwY2MiLCJpYXQiOjE3Mzc0NjI5MTd9.ZtDKKv_G-o753i1GvRj0ZeK4GpK72-NorRVefEQ8kFM

{
  "content": "Token auth rocks!",
  "important": false
}